# New Section

In [1]:
%cd /content/drive/My Drive/cs224n/assignment4
!python sanity_check.py 1d

/content/drive/My Drive/cs224n/assignment4
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
Running Sanity Check for Question 1d: Encode
--------------------------------------------------------------------------------
enc_hiddens Sanity Checks Passed!
dec_init_state[0] Sanity Checks Passed!
dec_init_state[1] Sanity Checks Passed!
--------------------------------------------------------------------------------
All Sanity Checks Passed for Question 1d: Encode!
--------------------------------------------------------------------------------


In [2]:
%cd /content/drive/My Drive/cs224n/assignment4
!python sanity_check.py 1e

/content/drive/My Drive/cs224n/assignment4
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
--------------------------------------------------------------------------------
Running Sanity Check for Question 1e: Decode
--------------------------------------------------------------------------------
torch.Size([23, 5, 3])
combined_outputs Sanity Checks Passed!
--------------------------------------------------------------------------------
All Sanity Checks Passed for Question 1e: Decode!
--------------------------------------------------------------------------------


In [3]:
%cd /content/drive/My Drive/cs224n/assignment4
!python sanity_check.py 1f

/content/drive/My Drive/cs224n/assignment4
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
--------------------------------------------------------------------------------
Running Sanity Check for Question 1f: Step
--------------------------------------------------------------------------------
dec_state[0] Sanity Checks Passed!
dec_state[1] Sanity Checks Passed!
combined_output  Sanity Checks Passed!
e_t Sanity Checks Passed!
--------------------------------------------------------------------------------
All Sanity Checks Passed for Question 1f: Step!
--------------------------------------------------------------------------------


In [0]:
tt1 = torch.tensor(([[1,2,3],
                     [2,3,4]]))  #(b, h) = (2, 3)
print('tt1 shape ', tt1.shape , '\n', tt1)


#(b, src_len, h) = (2, 4, 3)
tt2 = torch.tensor(([[[1,2,3],
                      [2,5,1],
                      [1,3,4],
                      [3,6,8]],
                     
                     [[2,3,4],
                      [5,1,8],
                      [3,4,6],
                      [6,8,4]]]))
print('tt2 shape ', tt2.shape, '\n', tt2)

print('tt1 unsqueeze at dim=2\n', tt1.unsqueeze(2))

# tt1_dot_tt2 = torch.bmm(tt1.unsqueeze(2), tt2)
# error: RuntimeError: Expected tensor to have size 1 at dimension 1, 
# but got size 4 for argument #2 'batch2' (while checking arguments for bmm)

tt1_dot_tt2 = torch.bmm(tt2, tt1.unsqueeze(2))
print("tt1 dott tt2\n", tt1_dot_tt2)

tt1_dot_tt2.squeeze()

tt1 shape  torch.Size([2, 3]) 
 tensor([[1, 2, 3],
        [2, 3, 4]])
tt2 shape  torch.Size([2, 4, 3]) 
 tensor([[[1, 2, 3],
         [2, 5, 1],
         [1, 3, 4],
         [3, 6, 8]],

        [[2, 3, 4],
         [5, 1, 8],
         [3, 4, 6],
         [6, 8, 4]]])
tt1 unsqueeze at dim=2
 tensor([[[1],
         [2],
         [3]],

        [[2],
         [3],
         [4]]])
tt1 dott tt2
 tensor([[[14],
         [15],
         [19],
         [39]],

        [[29],
         [45],
         [42],
         [52]]])


tensor([[14, 15, 19, 39],
        [29, 45, 42, 52]])

In [0]:
%cd /content/drive/My Drive/cs224n/assignment4
!sh run.sh vocab

/content/drive/My Drive/cs224n/assignment4
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
read in source sentences: ./en_es_data/train.es
read in target sentences: ./en_es_data/train.en
initialize source vocabulary ..
Traceback (most recent call last):
  File "vocab.py", line 216, in <module>
    vocab = Vocab.build(src_sents, tgt_sents, int(args['--size']), int(args['--freq-cutoff']))
  File "vocab.py", line 174, in build
    src = VocabEntry.from_corpus(src_sents, vocab_size, freq_cutoff)
  File "vocab.py", line 142, in from_corpus
    word_freq = Counter(chain(*corpus))
  File "/usr/lib/python3.6/collections/__init__.py", line 535, in __init__
    self.update(*args, **kwds)
  File "/usr/lib/python3.6/collections/__init__.py", line 622, in update
    _count_elements(self, iterable)
KeyboardInterrupt
^C


In [0]:
%cd /content/drive/My Drive/cs224n/assignment4
!sh run.sh train_local

In [0]:
%pip install -r gpu_requirements.txt

     |████████████████████████████████| 51kB 4.0MB/s 
ERROR: spacy 2.2.4 has requirement tqdm<5.0.0,>=4.38.0, but you'll have tqdm 4.29.1 which is incompatible.
  Found existing installation: tqdm 4.38.0
    Uninstalling tqdm-4.38.0:
      Successfully uninstalled tqdm-4.38.0


In [1]:
%cd /content/drive/My Drive/cs224n/assignment4
!sh run.sh train

Streaming output truncated to the last 5000 lines.
epoch 7, iter 41200, avg. loss 30.64, avg. ppl 4.24 cum. examples 38377, speed 8454.60 words/sec, time elapsed 3324.57 sec
epoch 7, iter 41210, avg. loss 29.53, avg. ppl 4.01 cum. examples 38697, speed 8792.25 words/sec, time elapsed 3325.35 sec
epoch 7, iter 41220, avg. loss 26.67, avg. ppl 3.75 cum. examples 39017, speed 7773.84 words/sec, time elapsed 3326.18 sec
epoch 7, iter 41230, avg. loss 30.50, avg. ppl 3.89 cum. examples 39337, speed 8679.18 words/sec, time elapsed 3327.01 sec
epoch 7, iter 41240, avg. loss 28.03, avg. ppl 4.10 cum. examples 39657, speed 8059.51 words/sec, time elapsed 3327.79 sec
epoch 7, iter 41250, avg. loss 29.15, avg. ppl 4.21 cum. examples 39977, speed 8382.23 words/sec, time elapsed 3328.57 sec
epoch 7, iter 41260, avg. loss 27.40, avg. ppl 3.98 cum. examples 40297, speed 8199.30 words/sec, time elapsed 3329.34 sec
epoch 7, iter 41270, avg. loss 25.25, avg. ppl 3.72 cum. examples 40617, speed 8337.63 w

In [2]:
%cd /content/drive/My Drive/cs224n/assignment4
!sh run.sh test
# b= 1, h = 256, h*2 = 512, src_len = 31

# Ybar_t [1, 512], expect (b, e+h)
# dec_state [1, 256], expect (b, h)
# dec_cell [1, 256], expect (b, h)
# exp_src_encodings [1, 31, 512], expect (b, src_len_h*2)
# exp_src_encodings_att_linear [1, 31, 512], expect (b, src_len)

/content/drive/My Drive/cs224n/assignment4
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
load test source sentences from [./en_es_data/test.es]
load test target sentences from [./en_es_data/test.en]
load model from model.bin
Decoding:   0% 0/8064 [00:00<?, ?it/s]/pytorch/aten/src/ATen/native/BinaryOps.cpp:81: UserWarning: Integer division of tensors using div or / is deprecated, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.
Decoding: 100% 8064/8064 [06:33<00:00, 20.51it/s]
Corpus BLEU: 35.60026767967568
